### ISSUE TITLE
hub runner with detection code

### ISSUE THREAD

**Issue by knl88** [SeaBee-no/seabeepy#11]
We can also extend the hub-runner [Dockerfile](https://github.com/SeaBee-no/seabeepy/blob/main/Dockerfile.runner)  with  the NR detection programs as used in https://github.com/SeaBee-no/seabeepy/blob/main/Dockerfile.runner. It can be done similar to hub main [dockerfile](https://github.com/SeaBee-no/dockerfiles/blob/6eb052f60592ac896c63274dba85a9933c0107fe/hub-main/Dockerfile#L154).

**Comment by 27am** [comment]
It seems I don't have the right to push to this repo
