### ISSUE TITLE
Dockerfile build error

### ISSUE THREAD

**Issue by 27am** [SeaBee-no/seabeepy#14]
When bulding the current [Dockerfile](https://github.com/SeaBee-no/seabeepy/blob/main/Dockerfile.runner) in the main branch I get a:

```
61.59   ERROR: Failed building wheel for fiona
61.59   Running setup.py clean for fiona
61.66   Building wheel for rasterio (pyproject.toml): started
96.29   Building wheel for rasterio (pyproject.toml): finished with status 'error'
96.30   error: subprocess-exited-with-error
96.30   
96.30   × Building wheel for rasterio (pyproject.toml) did not run successfully.
```

This is related to [this PR](https://github.com/SeaBee-no/seabeepy/pull/13) since I was testing the Dockerfile before and after changes. The Dockerfile in the PR raises the same error.

Does the original Dockerfile build smoothly @knl88?

**Comment by knl88** [comment]
It did so a week ago here https://github.com/SeaBee-no/seabeepy/actions/runs/6945337100. Does this have anything to do with  the osx architecture?
