### ISSUE TITLE
Processing of msi images

### ISSUE THREAD

**Issue by medyang** [SeaBee-no/seabeepy#9]
With msi images they will be divided into folders with a number like `001`,`002`  but the naming inside each folder can be the same so putting all the images in one folder can be difficult. Perhaps we should check if nodeodm can process folders:)

**Comment by knl88** [comment]
If you upload images with the same name but different paths nodeodm adds an underscore to the duplicate. So for an upload of `001/image1.JPG` and  `002/image1.JPG` we get an `img_list.txt` file that contains `image1.JPG` and `image1_.JPG`
